
GET http://localhost:3001/standgen

###

GET http://localhost:3001/standgen/6450d42633c3ee1ef89faa1e

###

POST http://localhost:3001/standgen/new
Content-Type: application/json

{
    "user": "Jotaro Kujo2",
    "personality": "Misogonist2",
    "name": "Star Platinum2",
    "appereance": "purple aztec-like humanoid mmmmmmmmmmmmmmmmmmm2",
    "standAbility": "oraoraoraoraora2"
    
}

###

POST http://localhost:3001/standgen/new
Content-Type: application/json

{
    "user": "User 1",
    "name": "Stand 1",
    "appereance": "appereance 1",
    "personality": "personality 1",
    "standAbility": "standAbility 1"
    
}

###

DELETE http://localhost:3001/standgen/delete/644c484ad9dcd0d225c33d76

###

PUT http://localhost:3001/standgen/update/stats/6450d42633c3ee1ef89faa1e
Content-Type: application/json

{
    "power": 1,
    "speed": 2,
    "range": 3,
    "durability": 4,
    "precision": 5,
    "potential": 5
}

###

PUT http://localhost:3001/standgen/update/name/6450ceb233c3ee1ef89fa9f7
Content-Type: application/json

{
    "name": "Rainbow in the Dark"
}

###

PUT http://localhost:3001/standgen/update/standAbility/644c470b7b8e16a3fc4c22dd
Content-Type: application/json

{
    "appereance": "Purple aztec-like humanoid mmmmmmmmmmmmmmmmmmm"
}

###

PUT http://localhost:3001/standgen/update/personality/644c470b7b8e16a3fc4c22dd
Content-Type: application/json

{
    "personality": "Misogonist"
}

###

PUT http://localhost:3001/standgen/update/standAbility/64431dbcb9007f4e42783980
Content-Type: application/json

{
    "standAbility": "oraoraoraoraora"
}

###

PUT http://localhost:3001/standgen/update/appereance/64431dbcb9007f4e42783980
Content-Type: application/json

{
    "appereance": "purple aztec-like humanoid mmmmmmmmmmmmmmmmmmm"
}